# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01c49362f5032114db60afb8fabdf2eb88fe682967e16c76d305fe5d7621d26171fd2be4a231d73f6052158ce46319ade994cf1c078eb14534fe4bc522f8faac

test:
  secret_key_base: 9826f70cb313e2516ac541e0491b7ff9f8dee4486a3cf83eb3eaa923e933ab93df28eedc9fd419aa58fcccd7ee25b6f96ef75ed9996a3bd0dd6cf4f9d982fbf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
